---
name: Docker Build and Push FlexAI experiment RAG

on:
  push:
    branches: [main]
  pull_request:
    paths:
    - code/rag/**
    - .github/workflows/docker-image.yml

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: rg.fr-par.scw.cloud/fcs-exp-rag

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get secrets
      uses: flexaihq/actions/setup-auth@main
      with:
        vault-enabled: 'true'
        vault-auth-secrets-auto: 'true'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: nologin
        password: ${{ env.SCW_REGISTRY_PAAS_PROJECT_RW_SECRET }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./code/rag/
        file: ./code/rag/Dockerfile
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: ${{ env.REGISTRY }}/fcs-exp-rag:${{ github.sha }}
