---
name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main

permissions:
  pull-requests: write
  contents: read

jobs:
  CI:
    uses: ./.github/workflows/base.yml
    if: |
      !github.event.pull_request.draft
